# Generated by Django 2.2.4 on 2019-09-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
